version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
    rebase-strategy: auto
    # Disable Dependabot version updates
    # We are only interested in security updates
    open-pull-requests-limit: 0
    groups:
      major:
        update-types:
          - 'major'
        applies-to: security-updates
      minor:
        update-types:
          - 'minor'
        applies-to: security-updates
      patch:
        update-types:
          - 'patch'
        applies-to: security-updates